### ISSUE TITLE
Cursor related...

### ISSUE THREAD

**Issue by Skishe** [MartyrPher/SMAPI-Android-Installer#17]
Is there a way to actually use the cursor (like left clicking or scrolling on mods that use some kind of UI)? 

Or is it actually built in the game itself?

**Comment by MartyrPher** [comment]
**Short Answer:** No, it really can't be used like a cursor.

**Long Answer:** The cursor is in the games files and can be drawn by the game, some mods actually draw the cursor, such as mods that use menus. The Android port has the method that draws the cursor but the devs left it blank since there is no mouse. The closest thing you can get to mouse controls is to use the `RightMouse` button in the Virtual Keyboard or create a `LeftMouse` that simulates a left click in Virtual Keyboard. The problem with the above (and it's kinda hard to explain) would be if you hold your finger in the spot you want to click and try to touch `RightMouse` on the VirtualKeyboard it would register as a touch in the middle of the two spots and not separately. I hope this is the info you were looking for! Cheers!

**Comment by Skishe** [comment]
The thing is that it attempts to exit the UI
