### ISSUE TITLE
Application Update

### ISSUE THREAD

**Issue by CreePyan** [MartyrPher/SMAPI-Android-Installer#28]
Maybe you can make the application by using it:

- Perform Stardew Valley Extract
- Then press the "Install DLL" button
- Then press play

This is good for people who want to install xnb files without having to extract, sign, install

**Comment by xelrix** [comment]
While i kinda agree with this approach, (something like ZaneYork's launcher), you can always install xnb mods by converting them to contentpatcher mod

**Comment by MartyrPher** [comment]
This idea is good but there is two reasons why this isn't going to be apart of my version.

1.  This would require the `StardewValley.dll` to be edited to point to the Content directory that was extracted from the apk, my approach so far goes without editing the DLL. ZaneYork heavily modified the DLL to accomplish different things. I don't see me editing the DLL in the future as it kind of defeats what SMAPI tries to accomplish.
2. Like xelrix mentioned, most XNB mods are converted to Content Patcher mods, the modding community frowns upon XNB mods since they cause more harm then good and a lot of CP modders have converted XNB mods to Content Patcher.

**Comment by CreePyan** [comment]
So?

There won't be an update like that?

**Comment by MartyrPher** [comment]
There won't be for the reasons listed above.

**Comment by CreePyan** [comment]
Thank you.... Now i close this issue
